### ISSUE TITLE
Failed to install on Linux

### ISSUE THREAD

**Issue by itsgifnotjiff** [b-data/jupyterlab-mojo-docker-stack#3]
Tried to install it on 

```shell
Linux NAME 5.15.0-50-generic #56-Ubuntu SMP Tue Sep 20 13:23:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

using `Docker version 24.0.6, build ed223bc` but I got to 

```shell
Step 53/90 : ENV PARENT_IMAGE=${BUILD_ON_IMAGE}${PYTHON_VERSION:+:}${PYTHON_VERSION}${CUDA_IMAGE_FLAVOR:+-}${CUDA_IMAGE_FLAVOR}     MODULAR_HOME=/opt/modular     MOJO_VERSION=${MOJO_VERSION%%-*}     NB_USER=${NB_USER}     NB_UID=${NB_UID}     JUPYTERHUB_VERSION=${JUPYTERHUB_VERSION}     JUPYTERLAB_VERSION=${JUPYTERLAB_VERSION}     CODE_SERVER_VERSION=${CODE_SERVER_VERSION}     GIT_VERSION=${GIT_VERSION}     GIT_LFS_VERSION=${GIT_LFS_VERSION}     PANDOC_VERSION=${PANDOC_VERSION}
failed to process "${MOJO_VERSION%%-*}": missing ':' in substitution
```

**Comment by benz0li** [comment]
@itsgifnotjiff Why don't you use the pre-built images? I.e. `glcr.b-data.ch/jupyterlab/mojo/base` or `glcr.b-data.ch/jupyterlab/mojo/scipy`?

**Comment by benz0li** [comment]
@itsgifnotjiff Variable expansion is only supported for [a limited set of Dockerfile instructions](https://docs.docker.com/reference/dockerfile/#environment-replacement).

If you want to build the images with a Docker version < 26.0.0, you need to add `# syntax=docker/dockerfile-upstream:master` at the very top of the `24.3.0.Dockerfile` or `latest.Dockerfile`.

**Comment by itsgifnotjiff** [comment]
> @itsgifnotjiff Why don't you use the pre-built images? I.e. `glcr.b-data.ch/jupyterlab/mojo/base` or `glcr.b-data.ch/jupyterlab/mojo/scipy`?

Should I do that sir? I just found your repo and assumed it is the "right" way to do it. My goal is to experiment with MAX and Mojo on an HPC with GPU clusters for atmospheric ML models (Graphcast and such). Does that fit this repo default or should I change to something else? 

Thank you so much for your wonderful work ☺️

**Comment by itsgifnotjiff** [comment]
> @itsgifnotjiff Variable expansion is only supported for [a limited set of Dockerfile instructions](https://docs.docker.com/reference/dockerfile/#environment-replacement).
> 
> If you want to build the images with a Docker version < 26.0.0, you need to add `# syntax=docker/dockerfile-upstream:master` at the very top of the `24.3.0.Dockerfile` or `latest.Dockerfile`.

This does not work sir. I get 

```shell
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/
```

Does the command

```shell
cd base && docker build \
  --build-arg MODULAR_VERSION=0.8.0 \
  --build-arg MOJO_VERSION=24.4.0 \
  --build-arg PYTHON_VERSION=3.12.4 \
  -t jupyterlab/mojo/base \
  -f latest.Dockerfile .
```
work for you out of the gate? I don't want to waste your time but I appreciate your guidance :)

**Comment by benz0li** [comment]
> > @itsgifnotjiff Why don't you use the pre-built images? I.e. `glcr.b-data.ch/jupyterlab/mojo/base` or `glcr.b-data.ch/jupyterlab/mojo/scipy`?
> 
> Should I do that sir? I just found your repo and assumed it is the "right" way to do it.

Either way is fine.

> My goal is to experiment with MAX and Mojo on an HPC with GPU clusters for atmospheric ML models (Graphcast and such). Does that fit this repo default or should I change to something else?

The current images provide just Mojo. 'MAX Engine'-based images will be published as soon as the [MAX Engine](https://www.modular.com/max/engine) supports Python 3.12.  
ℹ️ Currently, *only* [ Python 3.8 - 3.11](https://docs.modular.com/max/install#requirements) is supported.

Cross references:

* https://github.com/b-data/jupyterlab-mojo-docker-stack/issues/1
* https://github.com/modularml/max/issues/149

Furthermore, the MAX Engine does not support NVIDIA GPUs yet: https://docs.modular.com/engine/faq#what-hardware-is-currently-supported-by-max-engine

GPU accelerated 'MAX Engine'-based images will be published as soon as the MAX Engine supports Python 3.12 and NVIDIA GPUs.  
ℹ️ Supposedly this summer: https://twitter.com/Modular/status/1785131461345157140

Cross reference:

* https://github.com/b-data/jupyterlab-mojo-docker-stack/issues/2

> Thank you so much for your wonderful work ☺️

You are welcome.

**Comment by benz0li** [comment]
> > @itsgifnotjiff Variable expansion is only supported for [a limited set of Dockerfile instructions](https://docs.docker.com/reference/dockerfile/#environment-replacement).
> > If you want to build the images with a Docker version < 26.0.0, you need to add `# syntax=docker/dockerfile-upstream:master` at the very top of the `24.3.0.Dockerfile` or `latest.Dockerfile`.
> 
> This does not work sir. I get
> 
> ```shell
> DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
>             Install the buildx component to build images with BuildKit:
>             https://docs.docker.com/go/buildx/
> ```
> 
> Does the command
> 
> ```shell
> cd base && docker build \
>   --build-arg MODULAR_VERSION=0.8.0 \
>   --build-arg MOJO_VERSION=24.4.0 \
>   --build-arg PYTHON_VERSION=3.12.4 \
>   -t jupyterlab/mojo/base \
>   -f latest.Dockerfile .
> ```
> 
> work for you out of the gate? I don't want to waste your time but I appreciate your guidance :)

Yes.

To build 'MAX Engine'-based images yourself:

```bash
cd base
docker build \
  --build-arg MODULAR_VERSION=0.8.0 \
  --build-arg MODULAR_AUTH_KEY=<your-modular-auth-key> \
  --build-arg MOJO_VERSION=24.4.0 \
  --build-arg INSTALL_MAX=1 \
  --build-arg PYTHON_VERSION=3.11.9 \
  -t jupyterlab/mojo-max/base \
  -f latest.Dockerfile .
```

**Comment by benz0li** [comment]
Building yourself will only work, if you install the *latest* Docker Engine from Docker's `apt` repository.

Please follow the instructions for your platform (Ubuntu):

* https://docs.docker.com/engine/install/ubuntu/
* https://docs.docker.com/engine/install/linux-postinstall/

**Comment by benz0li** [comment]
@itsgifnotjiff Can this be closed?

**Comment by itsgifnotjiff** [comment]
Absolutely sir! I managed in another way. Sorry to clutter the issues.
